name: 'compas-actions.build'
description: 'Build and test COMPAS or its plugins'

inputs:
  test_lint:
    description: 'whether to test lint errors'
    required: true
    default: 'false'
  test_compas:
    description: 'whether to test with python -m compas'
    required: true
    default: 'false'
  command:
    description: 'the test command'
    required: true
    default: 'invoke test'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install cython --install-option='--no-cython-compile'
        pip install --no-cache-dir -r requirements-dev.txt

    - shell: bash
      run: |
        if [[ ${{ inputs.test_lint }} = "true" ]]; then
          invoke lint
        fi;

    - shell: bash
      run: |
        if [[ ${{ inputs.test_compas }} = "true" ]]; then
          python -m compas
        fi;

    - shell: bash
      run: ${{ inputs.test_command }}