name: 'compas-actions.build'
description: 'Build and test COMPAS or its plugins'

inputs:
  test_lint:
    description: 'whether to test lint errors'
    required: true
    default: 'false'
  test_compas:
    description: 'whether to test with python -m compas'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - shell: bash -l {0}
      run: |
        if [[ ${{ runner.os }} == "Windows" && -f env_win.yml ]]; then
          conda env create -f env_win.yml -n compas-build
          conda activate compas-build
        elif [[ ${{ runner.os }} == "macOS" && -f env_osx.yml ]]; then
          conda env create -f env_osx.yml -n compas-build
          conda activate compas-build
        elif [[ ${{ runner.os }} == "Linux" && -f env_linux.yml ]]; then
          conda env create -f env_linux.yml -n compas-build
          conda activate compas-build
        else
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
          pip install --no-cache-dir -r requirements-dev.txt
        fi

        if [[ ${{ inputs.test_lint }} = "true" ]]; then
          invoke lint
        fi;

        if [[ ${{ inputs.test_compas }} = "true" ]]; then
          python -m compas
        fi;
        
        invoke test