name: 'compas-actions.build'
description: 'Build and test COMPAS or its plugins'

runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install --upgrade pip
        pip install cython --install-option='--no-cython-compile'
      shell: bash
    - run: pip install --no-cache-dir -r requirements-dev.txt
      shell: bash
    - run: invoke lint
      shell: bash
    - run: python -m compas
      shell: bash
    - run: invoke test
      shell: bash